name: Blue-Green Deployment with Cypress

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Make deployment scripts executable
        run: chmod +x scripts/*.sh

      - name: Deploy to Green Environment
        run: ./scripts/deploy-to-green.sh

      - name: Wait for Green environment to be ready
        run: |
          for i in {1..30}; do
            if curl --output /dev/null --silent --head --fail http://localhost:3002; then
              echo "Green environment is up"
              break
            fi
            echo "Waiting for Green environment..."
            sleep 5
          done

      - name: Run Cypress Tests on Green Environment
        run: npx cypress run --env CYPRESS_BASE_URL=http://localhost:3002 --spec "cypress/e2e/green-tests.cy.js"

      - name: Switch Traffic to Green Environment
        if: success()
        run: ./scripts/switch-to-green.sh

      - name: Rollback to Blue Environment
        if: failure()
        run: ./scripts/rollback-to-blue.sh
